language: ruby
branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+/
env:
  global:
    - CODECLIMATE_REPO_TOKEN=151e29085225a0d503821bd67ad8d5dadddb7352fe0d585512c325990c85492b
rvm:
- jruby-1.7.0
- jruby-1.7.16
script:
- bundle exec rake
deploy:
  provider: rubygems
  api_key:
    secure: C9X1OQ07eVDPqOEcKQOOo+Li18J5VQ6uwsua6fNb7Mvzm5RVYKdaYMjan6gSJNkprxk5yDt/LQSZBBSSluO0yqxzyFFFBqzswPPKsYys5HVW45rFLFDs83e2YtgACEnXfNozuWoy0i3jgpN/P+eqrBlNFfuHpm4di7IBmeZimDY=
  gem: snmpjr
  on:
    tags: true
    repo: zenonas/snmpjr
    all_branches: true
